// Pokédex data — 158 capturable pokémon (gen 1 + extras). id, file, types, base atk/def/spd (PokeAPI).
const POKEDEX = [
  {id:1,name:"Bulbasaur",file:"bulbasaur.png",types:["grass", "poison"],atk:49,def:49,spd:45},
  {id:2,name:"Ivysaur",file:"ivysaur.png",types:["grass", "poison"],atk:62,def:63,spd:60},
  {id:3,name:"Venusaur",file:"venusaur.png",types:["grass", "poison"],atk:82,def:83,spd:80},
  {id:4,name:"Charmander",file:"charmander.png",types:["fire"],atk:52,def:43,spd:65},
  {id:5,name:"Charmeleon",file:"charmeleon.png",types:["fire"],atk:64,def:58,spd:80},
  {id:6,name:"Charizard",file:"charizard.png",types:["fire", "flying"],atk:84,def:78,spd:100},
  {id:7,name:"Squirtle",file:"squirtle.png",types:["water"],atk:48,def:65,spd:43},
  {id:8,name:"Wartortle",file:"wartortle.png",types:["water"],atk:63,def:80,spd:58},
  {id:9,name:"Blastoise",file:"blastoise.png",types:["water"],atk:83,def:100,spd:78},
  {id:10,name:"Caterpie",file:"caterpie.png",types:["bug"],atk:30,def:35,spd:45},
  {id:11,name:"Metapod",file:"metapod.png",types:["bug"],atk:20,def:55,spd:30},
  {id:12,name:"Butterfree",file:"butterfree.png",types:["bug", "flying"],atk:45,def:50,spd:70},
  {id:13,name:"Weedle",file:"weedle.png",types:["bug", "poison"],atk:35,def:30,spd:50},
  {id:14,name:"Kakuna",file:"kakuna.png",types:["bug", "poison"],atk:25,def:50,spd:35},
  {id:15,name:"Beedrill",file:"beedrill.png",types:["bug", "poison"],atk:90,def:40,spd:75},
  {id:16,name:"Pidgey",file:"pidgey.png",types:["normal", "flying"],atk:45,def:40,spd:56},
  {id:17,name:"Pidgeotto",file:"pidgeotto.png",types:["normal", "flying"],atk:60,def:55,spd:71},
  {id:18,name:"Pidgeot",file:"pidgeot.png",types:["normal", "flying"],atk:80,def:75,spd:101},
  {id:19,name:"Rattata",file:"rattata.png",types:["normal"],atk:56,def:35,spd:72},
  {id:20,name:"Raticate",file:"raticate.png",types:["normal"],atk:81,def:60,spd:97},
  {id:21,name:"Spearow",file:"spearow.png",types:["normal", "flying"],atk:60,def:30,spd:70},
  {id:22,name:"Fearow",file:"fearow.png",types:["normal", "flying"],atk:90,def:65,spd:100},
  {id:23,name:"Ekans",file:"ekans.png",types:["poison"],atk:60,def:44,spd:55},
  {id:24,name:"Arbok",file:"arbok.png",types:["poison"],atk:95,def:69,spd:80},
  {id:25,name:"Pikachu",file:"pikachu.png",types:["electric"],atk:55,def:40,spd:90},
  {id:26,name:"Raichu",file:"raichu.png",types:["electric"],atk:90,def:55,spd:110},
  {id:27,name:"Sandshrew",file:"sandshrew.png",types:["ground"],atk:75,def:85,spd:40},
  {id:28,name:"Sandslash",file:"sandslash.png",types:["ground"],atk:100,def:110,spd:65},
  {id:29,name:"Nidoran F",file:"nidoranf.png",types:["poison"],atk:47,def:52,spd:41},
  {id:30,name:"Nidorina",file:"nidorina.png",types:["poison"],atk:62,def:67,spd:56},
  {id:31,name:"Nidoqueen",file:"nidoqueen.png",types:["poison", "ground"],atk:92,def:87,spd:76},
  {id:32,name:"Nidoran M",file:"nidoranm.png",types:["poison"],atk:57,def:40,spd:50},
  {id:33,name:"Nidorino",file:"nidorino.png",types:["poison"],atk:72,def:57,spd:65},
  {id:34,name:"Nidoking",file:"nidoking.png",types:["poison", "ground"],atk:102,def:77,spd:85},
  {id:35,name:"Clefairy",file:"clefairy.png",types:["fairy"],atk:45,def:48,spd:35},
  {id:36,name:"Clefable",file:"clefable.png",types:["fairy"],atk:70,def:73,spd:60},
  {id:37,name:"Vulpix",file:"vulpix.png",types:["fire"],atk:41,def:40,spd:65},
  {id:38,name:"Ninetales",file:"ninetales.png",types:["fire"],atk:76,def:75,spd:100},
  {id:39,name:"Jigglypuff",file:"jigglypuff.png",types:["normal", "fairy"],atk:45,def:20,spd:20},
  {id:40,name:"Wigglytuff",file:"wigglytuff.png",types:["normal", "fairy"],atk:70,def:45,spd:45},
  {id:41,name:"Zubat",file:"zubat.png",types:["poison", "flying"],atk:45,def:35,spd:55},
  {id:42,name:"Golbat",file:"golbat.png",types:["poison", "flying"],atk:80,def:70,spd:90},
  {id:43,name:"Oddish",file:"oddish.png",types:["grass", "poison"],atk:50,def:55,spd:30},
  {id:44,name:"Gloom",file:"gloom.png",types:["grass", "poison"],atk:65,def:70,spd:40},
  {id:45,name:"Vileplume",file:"vileplume.png",types:["grass", "poison"],atk:80,def:85,spd:50},
  {id:46,name:"Paras",file:"paras.png",types:["bug", "grass"],atk:70,def:55,spd:25},
  {id:47,name:"Parasect",file:"parasect.png",types:["bug", "grass"],atk:95,def:80,spd:30},
  {id:48,name:"Venonat",file:"venonat.png",types:["bug", "poison"],atk:55,def:50,spd:45},
  {id:49,name:"Venomoth",file:"venomoth.png",types:["bug", "poison"],atk:65,def:60,spd:90},
  {id:50,name:"Diglett",file:"diglett.png",types:["ground"],atk:55,def:25,spd:95},
  {id:51,name:"Dugtrio",file:"dugtrio.png",types:["ground"],atk:100,def:50,spd:120},
  {id:52,name:"Meowth",file:"meowth.png",types:["normal"],atk:45,def:35,spd:90},
  {id:53,name:"Persian",file:"persian.png",types:["normal"],atk:70,def:60,spd:115},
  {id:54,name:"Psyduck",file:"psyduck.png",types:["water"],atk:52,def:48,spd:55},
  {id:55,name:"Golduck",file:"golduck.png",types:["water"],atk:82,def:78,spd:85},
  {id:56,name:"Mankey",file:"mankey.png",types:["fighting"],atk:80,def:35,spd:70},
  {id:57,name:"Primeape",file:"primeape.png",types:["fighting"],atk:105,def:60,spd:95},
  {id:58,name:"Growlithe",file:"growlithe.png",types:["fire"],atk:70,def:45,spd:60},
  {id:59,name:"Arcanine",file:"arcanine.png",types:["fire"],atk:110,def:80,spd:95},
  {id:60,name:"Poliwag",file:"poliwag.png",types:["water"],atk:50,def:40,spd:90},
  {id:61,name:"Poliwhirl",file:"poliwhirl.png",types:["water"],atk:65,def:65,spd:90},
  {id:62,name:"Poliwrath",file:"poliwrath.png",types:["water", "fighting"],atk:95,def:95,spd:70},
  {id:63,name:"Abra",file:"abra.png",types:["psychic"],atk:20,def:15,spd:90},
  {id:64,name:"Kadabra",file:"kadabra.png",types:["psychic"],atk:35,def:30,spd:105},
  {id:65,name:"Alakazam",file:"alakazam.png",types:["psychic"],atk:50,def:45,spd:120},
  {id:66,name:"Machop",file:"machop.png",types:["fighting"],atk:80,def:50,spd:35},
  {id:67,name:"Machoke",file:"machoke.png",types:["fighting"],atk:100,def:70,spd:45},
  {id:68,name:"Machamp",file:"machamp.png",types:["fighting"],atk:130,def:80,spd:55},
  {id:69,name:"Bellsprout",file:"bellsprout.png",types:["grass", "poison"],atk:75,def:35,spd:40},
  {id:70,name:"Weepinbell",file:"weepinbell.png",types:["grass", "poison"],atk:90,def:50,spd:55},
  {id:71,name:"Victreebel",file:"victreebel.png",types:["grass", "poison"],atk:105,def:65,spd:70},
  {id:72,name:"Tentacool",file:"tentacool.png",types:["water", "poison"],atk:40,def:35,spd:70},
  {id:73,name:"Tentacruel",file:"tentacruel.png",types:["water", "poison"],atk:70,def:65,spd:100},
  {id:74,name:"Geodude",file:"geodude.png",types:["rock", "ground"],atk:80,def:100,spd:20},
  {id:75,name:"Graveler",file:"graveler.png",types:["rock", "ground"],atk:95,def:115,spd:35},
  {id:76,name:"Golem",file:"golem.png",types:["rock", "ground"],atk:120,def:130,spd:45},
  {id:77,name:"Ponyta",file:"ponyta.png",types:["fire"],atk:85,def:55,spd:90},
  {id:78,name:"Rapidash",file:"rapidash.png",types:["fire"],atk:100,def:70,spd:105},
  {id:79,name:"Slowpoke",file:"slowpoke.png",types:["water", "psychic"],atk:65,def:65,spd:15},
  {id:80,name:"Slowbro",file:"slowbro.png",types:["water", "psychic"],atk:75,def:110,spd:30},
  {id:81,name:"Magnemite",file:"magnemite.png",types:["electric", "steel"],atk:35,def:70,spd:45},
  {id:82,name:"Magneton",file:"magneton.png",types:["electric", "steel"],atk:60,def:95,spd:70},
  {id:83,name:"Farfetchd",file:"farfetchd.png",types:["normal", "flying"],atk:90,def:55,spd:60},
  {id:84,name:"Doduo",file:"doduo.png",types:["normal", "flying"],atk:85,def:45,spd:75},
  {id:85,name:"Dodrio",file:"dodrio.png",types:["normal", "flying"],atk:110,def:70,spd:110},
  {id:86,name:"Seel",file:"seel.png",types:["water"],atk:45,def:55,spd:45},
  {id:87,name:"Dewgong",file:"dewgong.png",types:["water", "ice"],atk:70,def:80,spd:70},
  {id:88,name:"Grimer",file:"grimer.png",types:["poison"],atk:80,def:50,spd:25},
  {id:89,name:"Muk",file:"muk.png",types:["poison"],atk:105,def:75,spd:50},
  {id:90,name:"Shellder",file:"shellder.png",types:["water"],atk:65,def:100,spd:40},
  {id:91,name:"Cloyster",file:"cloyster.png",types:["water", "ice"],atk:95,def:180,spd:70},
  {id:92,name:"Gastly",file:"gastly.png",types:["ghost", "poison"],atk:35,def:30,spd:80},
  {id:93,name:"Haunter",file:"haunter.png",types:["ghost", "poison"],atk:50,def:45,spd:95},
  {id:94,name:"Gengar",file:"gengar.png",types:["ghost", "poison"],atk:65,def:60,spd:110},
  {id:95,name:"Onix",file:"onix.png",types:["rock", "ground"],atk:45,def:160,spd:70},
  {id:96,name:"Drowzee",file:"drowzee.png",types:["psychic"],atk:48,def:45,spd:42},
  {id:97,name:"Hypno",file:"hypno.png",types:["psychic"],atk:73,def:70,spd:67},
  {id:98,name:"Krabby",file:"krabby.png",types:["water"],atk:105,def:90,spd:50},
  {id:99,name:"Kingler",file:"kingler.png",types:["water"],atk:130,def:115,spd:75},
  {id:100,name:"Voltorb",file:"voltorb.png",types:["electric"],atk:30,def:50,spd:100},
  {id:101,name:"Electrode",file:"electrode.png",types:["electric"],atk:50,def:70,spd:150},
  {id:102,name:"Exeggcute",file:"exeggcute.png",types:["grass", "psychic"],atk:40,def:80,spd:40},
  {id:103,name:"Exeggutor",file:"exeggutor.png",types:["grass", "psychic"],atk:95,def:85,spd:55},
  {id:104,name:"Cubone",file:"cubone.png",types:["ground"],atk:50,def:95,spd:35},
  {id:105,name:"Marowak",file:"marowak.png",types:["ground"],atk:80,def:110,spd:45},
  {id:106,name:"Hitmonlee",file:"hitmonlee.png",types:["fighting"],atk:120,def:53,spd:87},
  {id:107,name:"Hitmonchan",file:"hitmonchan.png",types:["fighting"],atk:105,def:79,spd:76},
  {id:108,name:"Lickitung",file:"lickitung.png",types:["normal"],atk:55,def:75,spd:30},
  {id:109,name:"Koffing",file:"koffing.png",types:["poison"],atk:65,def:95,spd:35},
  {id:110,name:"Weezing",file:"weezing.png",types:["poison"],atk:90,def:120,spd:60},
  {id:111,name:"Rhyhorn",file:"rhyhorn.png",types:["ground", "rock"],atk:85,def:95,spd:25},
  {id:112,name:"Rhydon",file:"rhydon.png",types:["ground", "rock"],atk:130,def:120,spd:40},
  {id:113,name:"Chansey",file:"chansey.png",types:["normal"],atk:5,def:5,spd:50},
  {id:114,name:"Tangela",file:"tangela.png",types:["grass"],atk:55,def:115,spd:60},
  {id:115,name:"Kangaskhan",file:"kangaskhan.png",types:["normal"],atk:95,def:80,spd:90},
  {id:116,name:"Horsea",file:"horsea.png",types:["water"],atk:40,def:70,spd:60},
  {id:117,name:"Seadra",file:"seadra.png",types:["water"],atk:65,def:95,spd:85},
  {id:118,name:"Goldeen",file:"goldeen.png",types:["water"],atk:67,def:60,spd:63},
  {id:119,name:"Seaking",file:"seaking.png",types:["water"],atk:92,def:65,spd:68},
  {id:120,name:"Staryu",file:"staryu.png",types:["water"],atk:45,def:55,spd:85},
  {id:121,name:"Starmie",file:"starmie.png",types:["water", "psychic"],atk:75,def:85,spd:115},
  {id:122,name:"Mr. Mime",file:"mr_mime.png",types:["psychic", "fairy"],atk:45,def:65,spd:90},
  {id:123,name:"Scyther",file:"scyther.png",types:["bug", "flying"],atk:110,def:80,spd:105},
  {id:124,name:"Jynx",file:"jynx.png",types:["ice", "psychic"],atk:50,def:35,spd:95},
  {id:125,name:"Electabuzz",file:"electabuzz.png",types:["electric"],atk:83,def:57,spd:105},
  {id:126,name:"Magmar",file:"magmar.png",types:["fire"],atk:95,def:57,spd:93},
  {id:127,name:"Pinsir",file:"pinsir.png",types:["bug"],atk:125,def:100,spd:85},
  {id:128,name:"Tauros",file:"tauros.png",types:["normal"],atk:100,def:95,spd:110},
  {id:129,name:"Magikarp",file:"magikarp.png",types:["water"],atk:10,def:55,spd:80},
  {id:130,name:"Gyarados",file:"gyarados.png",types:["water", "flying"],atk:125,def:79,spd:81},
  {id:131,name:"Lapras",file:"lapras.png",types:["water", "ice"],atk:85,def:80,spd:60},
  {id:132,name:"Ditto",file:"ditto.png",types:["normal"],atk:48,def:48,spd:48},
  {id:133,name:"Eevee",file:"eevee.png",types:["normal"],atk:55,def:50,spd:55},
  {id:134,name:"Vaporeon",file:"vaporeon.png",types:["water"],atk:65,def:60,spd:65},
  {id:135,name:"Jolteon",file:"jolteon.png",types:["electric"],atk:65,def:60,spd:130},
  {id:136,name:"Flareon",file:"flareon.png",types:["fire"],atk:130,def:60,spd:65},
  {id:137,name:"Porygon",file:"porygon.png",types:["normal"],atk:60,def:70,spd:40},
  {id:138,name:"Omanyte",file:"omanyte.png",types:["rock", "water"],atk:40,def:100,spd:35},
  {id:139,name:"Omastar",file:"omastar.png",types:["rock", "water"],atk:60,def:125,spd:55},
  {id:140,name:"Kabuto",file:"kabuto.png",types:["rock", "water"],atk:80,def:90,spd:55},
  {id:141,name:"Kabutops",file:"kabutops.png",types:["rock", "water"],atk:115,def:105,spd:80},
  {id:142,name:"Aerodactyl",file:"aerodactyl.png",types:["rock", "flying"],atk:105,def:65,spd:130},
  {id:143,name:"Snorlax",file:"snorlax.png",types:["normal"],atk:110,def:65,spd:30},
  {id:144,name:"Articuno",file:"articuno.png",types:["ice", "flying"],atk:85,def:100,spd:85},
  {id:145,name:"Zapdos",file:"zapdos.png",types:["electric", "flying"],atk:90,def:85,spd:100},
  {id:146,name:"Moltres",file:"moltres.png",types:["fire", "flying"],atk:100,def:90,spd:90},
  {id:147,name:"Dratini",file:"dratini.png",types:["dragon"],atk:64,def:45,spd:50},
  {id:148,name:"Dragonair",file:"dragonair.png",types:["dragon"],atk:84,def:65,spd:70},
  {id:149,name:"Dragonite",file:"dragonite.png",types:["dragon", "flying"],atk:134,def:95,spd:80},
  {id:150,name:"Mewtwo",file:"mewtwo.png",types:["psychic"],atk:110,def:90,spd:130},
  {id:151,name:"Mew",file:"mew.png",types:["psychic"],atk:100,def:100,spd:100},
  {id:197,name:"Umbreon",file:"umbreon.png",types:["dark"],atk:65,def:110,spd:65},
  {id:282,name:"Gardevoir",file:"gardevoir.png",types:["psychic", "fairy"],atk:65,def:65,spd:80},
  {id:392,name:"Infernape",file:"infernape.png",types:["fire", "fighting"],atk:104,def:71,spd:108},
  {id:445,name:"Garchomp",file:"garchomp.png",types:["dragon", "ground"],atk:130,def:95,spd:102},
  {id:448,name:"Lucario",file:"lucario.png",types:["fighting", "steel"],atk:110,def:70,spd:90},
  {id:658,name:"Greninja",file:"greninja.png",types:["water", "dark"],atk:95,def:67,spd:122},
  {id:700,name:"Sylveon",file:"sylveon.png",types:["fairy"],atk:65,def:65,spd:60},
];
